### ISSUE TITLE
Broken snippets (using placeholders in return values)

### ISSUE THREAD

**Issue by gruvw** [gruvw/latex-setup#2]
Update the snippets that use placeholders in return values.

Cf. [draivin/hsnips#97 v0.2.4 broke placeholders in return value](https://github.com/draivin/hsnips/issues/97).

Meanwhile, downgrade to v0.2.3 of the extension.

**Comment by A6669** [comment]
thank you, but we cannot use 0.2.3 forever, is there some way to use the newest hsnip without losing compatibility with your latex-step.

**Comment by gruvw** [comment]
I did not say that I will use v0.2.3 forever, I just wait for the [draivin/hsnips#97](https://github.com/draivin/hsnips/issues/97) issue to close (new placeholder system) and I will update the snippets at that time.

But we are on GitHub, so if you want, I would be happy to accept a pull request that solve the compatibility with the new version.

I just created this issue because we need to solve this, so it's in the plan to fix the snippets broken by v0.2.4.
We now have a place (here) to discuss it and to work our way to a fix.

**Comment by gruvw** [comment]
Hello, I am happy to announce that the snippets have been updated and now use the new tabstops system (see https://github.com/draivin/hsnips/issues/97#issuecomment-997126076).

The commit fixing the compatibility issue: https://github.com/gruvw/latex-setup/commit/d35eb31c98c2c717c8e33f0ef2f05f91b515b7d5

You can now update with the latest version of the hsnips extentions and all the snippets in this repository should work as intended.

**Note**: feel free to open a new issue if some of my snippets are not working properly
