### ISSUE TITLE
Greek letters seem to be broken

### ISSUE THREAD

**Issue by tomasrei** [gruvw/latex-setup#3]
Hi, thanks for the great snippets!

It seems like some of the greek letters don't work. I haven't tried them all, but so far only za works and that produces \zeta and not \alpha. Any ideas?

**Comment by tomasrei** [comment]
Nevermind. I didn't realize they were context based. It works inside "mathmode" just fine. You can remove this if you want. Sorry!

**Comment by gruvw** [comment]
No problem!  
Thanks for contributing anyway :)
